services:
  mysql:
    image: mysql:latest
    container_name: social_network_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - social_network_mysql_volume:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  social_network_mysql_volume:
    driver: local
    driver_opts:
      type: none
      device: ~/docker/social_network_mysql_data
      o: bind
